// app/layout.tsx
import "../styles/globals.css";
import { Ovo } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/layout/Header";
import { store } from "@/redux/store";
import CartProvider from "@/components/layout/CartProvider";

const inter = Ovo({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
